module.exports = {
  extends: ['stylelint-config-standard', 'stylelint-order'],
  plugins: ['stylelint-order'],
  rules: {
    'rule-empty-line-before': 'never',
    'order/properties-order': [
      { unspecified: 'bottom' },
      {
        emptyLineBefore: 'never',
        groupName: 'layout',
        properties: [
          'position',
          'z-index',
          'display',
          'grid',
          'grid-area',
          'grid-auto-columns',
          'grid-auto-flow',
          'grid-auto-rows',
          'grid-column',
          'grid-column-end',
          'grid-column-gap',
          'grid-column-start',
          'grid-gap',
          'grid-row',
          'grid-row-end',
          'grid-row-gap',
          'grid-row-start',
          'grid-template',
          'grid-template-areas',
          'grid-template-columns',
          'grid-template-rows',
          'align-content',
          'align-items',
          'align-self',
          'flex',
          'flex-basis',
          'flex-direction',
          'flex-flow',
          'flex-grow',
          'flex-shrink',
          'flex-wrap',
          'justify-content',
          'order',
          'float',
        ]
      },
      {
        emptyLineBefore: 'never',
        groupName: 'box model',
        properties: [
          'width',
          'height',
          'margin',
          'margin-top',
          'margin-right',
          'margin-bottom',
          'margin-left',
          'padding',
          'padding-top',
          'padding-right',
          'padding-bottom',
          'padding-left',
          'box-shadow',
          'background',
          'background-attachment',
          'background-blend-mode',
          'background-clip',
          'background-color',
          'background-image',
          'background-origin',
          'background-position',
          'background-repeat',
          'background-size',
          'border',
          'border-bottom',
          'border-bottom-color',
          'border-bottom-left-radius',
          'border-bottom-right-radius',
          'border-bottom-style',
          'border-bottom-width',
          'border-color',
          'border-left',
          'border-left-color',
          'border-left-style',
          'border-left-width',
          'border-radius',
          'border-right',
          'border-right-color',
          'border-right-style',
          'border-right-width',
          'border-style',
          'border-top',
          'border-top-color',
          'border-top-style',
          'border-top-width',
          'border-width'
        ]
      },
      {
        emptyLineBefore: 'never',
        groupName: 'font',
        properties: [
          'transition',
          'transition-delay',
          'transition-duration',
          'transition-property',
          'transition-timing-function',
        ]
      },
      {
        emptyLineBefore: 'never',
        groupName: 'typography',
        properties: [
          'color',
          'font-family',
          'font-size',
          'font-weight',
          'text-align',
          'text-shadow',
          'text-transform'
        ]
      },
      {
        emptyLineBefore: 'never',
        groupName: 'misc',
        properties: [
        ]
      },
    ]
  }
}
